meta_product_name: "Football Bay"
meta_title: "Football Bay Come and play with us!"
meta_description: "New arrival for football passionate and not only. Football Bay is an app helping peple find a place where they can play football anytime"
meta_image: "football_bay.jpg"
twitter_account: "@footballbay1"